# Site settings
name: Hafeezul Raziq
title: Hafeezul Raziq | Data Enthusiast
description: Data-driven analyst with a strong foundation in mathematics, passionate about leveraging data science and analytics to uncover insights and drive impactful decisions
url: https://hafeezulrzq.github.io/
baseurl: ''
email: hafeezul.rzq@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:hafeezul.rzq@gmail.com
  - title: instagram
    url: https://instagram.com/hafeezulrzq
  - title: github
    url: https://github.com/hafeezulrzq
  - title: linkedin
    url: https://www.linkedin.com/in/hafeezul-raziq/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
